#!/usr/bin/env python
from misc.utility.scons_hints import *
import ctypes
from SCons.Script import *

# Import
Import("env")
Import("env_modules")

# Clone Module Environment
env_meshex = env_modules.Clone()

# Add Source Files
env_meshex.add_source_files(env.modules_sources, "*.cpp")
